### ISSUE TITLE
helm-exwm-build-source builds a source that does not refresh automatically

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm-exwm#2]
I am a bit confused about the refresh mechanism of Helm.

@thierryvolpiatto: Can you help here?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I am a bit confused about the refresh mechanism of Helm.
>
> @thierryvolpiatto: Can you help here?

I have added a comment on helm-exwm first commit, but I am unsure what's
going wrong, can you elaborate on what is confusing you?

-- 
Thierry

**Comment by Ambrevar** [comment]
In the heat of the coding, I had tried this:

    :candidates (function (lambda () (helm-exwm-candidates filter)))

And it did not work, which is what had puzzled me.  Today I tried again: it does work.  So I assume this was a simple random mistake of my own.

What do you think of my solution?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> In the heat of the coding, I had tried this:
>
> :candidates (function (lambda () (helm-exwm-candidates filter)))

You don't need to quote lambdas with either #' or '.

> And it did not work, which is what had puzzled me. Today I tried again: it does work. So I assume this was a simple random mistake of my own.
>
> What do you think of my solution?

If the list is a fixed list (i.e. no buffer added in background during
helm session) I suggest you use an init function that load your
candidates in a cache and use this cache as candidates attr.

I saw also you have an update attr calling same function than
candidates, it is unneeded (it have no effect).

The update attr is used to e.g. setup a variable before calling init
function.  So when you force-update the update fn is called, then the
init function and then helm is updating using the candidates fn (or var).

-- 
Thierry

**Comment by Ambrevar** [comment]
> If the list is a fixed list (i.e. no buffer added in background during
> helm session) I suggest you use an init function that load your
> candidates in a cache and use this cache as candidates attr.

It is a list of all windows matched by the filter (usually windows of the same class).
For instance, popping up a new web browser window should add a buffer to that list.
So no, it's not a fixed list.

**Comment by Ambrevar** [comment]
No issue so far, I'm closing this.
