### ISSUE TITLE
'helm-source-names-using-follow is undefined

### ISSUE THREAD

**Issue by moritzschaefer** [emacs-helm/helm-exwm#7]
helm-source-names-using-follow is undefined and 

    (add-to-list 'helm-source-names-using-follow "EXWM buffers")

fails. Indeed searching the repository only references the name in the README..

https://github.com/emacs-helm/helm-exwm/search?q=helm-source-names-using-follow&unscoped_q=helm-source-names-using-follow

**Comment by Ambrevar** [comment]
There might be something wrong with your config.
`helm-source-names-using-follow` is defined in `helm.el`.

Did you `(require 'helm)`?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> There might be something wrong with your config.
> helm-source-names-using-follow is defined in helm.el.
>
> Did you (require 'helm)?

Also, read carefully the documentation, normally you should not have to
configure yourself this variable when you set
`helm-follow-mode-persistent` to non-nil.

--
Thierry

**Comment by moritzschaefer** [comment]
Thanks for the clarification!
